### ISSUE TITLE
NeurIPS paper 

### ISSUE THREAD

**Issue by Justinezgh** [Justinezgh/SBI-Diff-Simulator#16]
ok so from what I understand, that's the plan: 

# Score constrainable Normalizing Flows

1.  Introduction 
2. Conventional Normalizing Flows are Not Smooth
3. Differentiable NFs
    - Smooth NF (@Justinezgh) 
    - ODE Flow (@Justinezgh / @EiffL ?)
4. Applications 
    a. Learn distribution (2moons and swiss roll?) from **samples only**  using nll loss and score matching (so we have to approximate the score). (@b-remy ?)
    b. SBI (@Justinezgh)
    c.  High dimensionality problem with tractable log probability [like this](https://github.com/astrodeepnet/sbi_experiments/blob/u/EiffL/lensing_simuilation/notebooks/lensing_sims/AnalyticLensingSimulator_SIREN_5d.ipynb) (@EiffL)

**Comment by EiffL** [comment]
I've  made a flow variant of my previous notebook which was using SIRENs [here](https://colab.research.google.com/drive/1xibXhT8YhRjFzq5sYGIV_RGIXG9l7TR5?usp=sharing)

![image](https://user-images.githubusercontent.com/861591/168611682-fd19ff3d-e9e4-4af8-93ab-5a93fe17a4fc.png)
