### ISSUE TITLE
Adding a SCANDAL implementation on Lotka-Volterra

### ISSUE THREAD

**Issue by EiffL** [Justinezgh/SBI-Diff-Simulator#5]
This issue is to discuss how to implement a SCANDAL for the Lotka-Volterra problem. 

#### Size of problem
In the original paper, a 5 points problem is used, but in SBI Benchmark, they use 10 points (so an observation vector of size 20) instead. I think it would make more sense to try to adopt the SBIBM setting.

#### Architecture
The observations are time series, so I don't think it makes much sense to model them as a realNVP with last half conditionned on first half. We should do something like next time step conditioned on previous one. Either going full MAF, or a slightly better realNVP variable ordering.

**Comment by EiffL** [comment]
So, one comment @Justinezgh, if you want to restrict the size of the sample to 5 points, here is how you would do it:
```python
    (log_prob, sample), score =  get_samples_and_scores(partial(lotka_volterra, ts=jnp.linspace(0,18.9,5)), 
                                                        key, 
                                                        batch_size=batch_size, score_type='conditional')

```

**Comment by Justinezgh** [comment]
ok I did it with ` ts=jnp.linspace(0,10,5) ` but I'll change it

**Comment by EiffL** [comment]
or actually maybe this is even better 
```
jnp.linspace(0,18.9,10)[::2]
```
because this way we can also do `observation[::2]`

**Comment by Justinezgh** [comment]
I used our flow for scandal and got these results for the likelihood:
![image](https://user-images.githubusercontent.com/72011736/167219635-ff14f58f-2265-4753-9266-7679de2506f8.png)
and I don't know what I'm doing wrong but the posterior looks like this:
![image](https://user-images.githubusercontent.com/72011736/167219813-d6e46657-e048-4250-8f41-9f59f848f3d6.png)
 [notebook](https://github.com/Justinezgh/SBI-Diff-Simulator/blob/u/Justinezgh/ourmethod/notebooks/Scandal_on_LV.ipynb)

**Comment by Justinezgh** [comment]
(the true likelihood is
![image](https://user-images.githubusercontent.com/72011736/167223439-3ebaa7bf-1cae-41b1-bea8-bb3a86c36238.png)
)
